### ISSUE TITLE
What is `v`?

### ISSUE THREAD

**Issue by RAbraham** [guitarvydas/arith0d#5]
Hi Paul
In your example, https://github.com/guitarvydas/arith0d/blob/main/ex1.math

what is `v` or where does the value come from?

**Comment by guitarvydas** [comment]
This example is just a t2t (text-to-text) transpiler. The string `v * (42 - 1) / 9^3` is just a string of characters. So `v` is just a character at this point. The component `Transpile` inhales characters and exhales some characters.

The point of this example is to show how to transpile a generic syntax into a more-specific syntax suitable for 4 different languages (JS, Python, WASM, CL).

Consider the Python transpiler (arith.ohm + arithpy.rwr). It inhales the string `v * (42 - 1) / 9^3` and exhales a different string `v * 42 - 1 / 9**3` which is a legal Python *expression*. The expression is kinda useless on its own - we probably need to wrap some Python-esque boiler-plate code around it ("def ...", etc.) to make it useful.

Maybe it should print out this string of characters:
```
def f (v):
    return v * 42 - 1 / 9**3

print (f (42))
```

If you save the above string in a file, say `junk.py` and give it to the Python compiler, the string will be considered to be a program and the Python compiler will check it, compile it and run it.

Try it `python3 junk.py`.

The parser does more than just rewriting the input string. It checks for syntax errors along the way. Arith0D a fairly simple example, so it doesn't look very impressive...

Exercise: hack on `artihpy.rwr` to make it emit a full Python program that you can run using the python command. In the process, you'll need to guess at what the RWR syntax is. My belief is that the RWR syntax is so simple that you will be able to modify the code faster by guessing than by reading the RWR specification (when I write one). I will gladly help, if you are confused or need further assistance.

Note that `«` and `»` are Unicode characters. I have them bound to keystrokes in my editor, but you can just copy/paste them from other parts of `arithpy.rwr`.
